name: Daily Schedule Generator

on:
  push:      # <--- THIS IS THE NEW PART
    branches:
      - main
    paths:
      - 'generate_schedule.py' # Only run if the script changes
  schedule:
    - cron: '0 16 * * *' # Runs at 5:00 AM Sydney Time
  workflow_dispatch:      # Allows manual click

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Libraries
        run: pip install matplotlib

      - name: Run Generator
        run: python generate_schedule.py

      - name: Commit and Push Images
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Auto-update daily schedule [skip ci]"
          file_pattern: "*.png"
